# Initialization  

The simplex method starts at a vertex and tries to find an adjacent vertex with a higher objective value.  We can start this process at the origin if it is a vertex of the feasible region. However, this is not always the case.
The origin is in the feasible region of the standard linear program \@ref(eq:standard-lp) if and only if $b_i \ge 0$ for all $1 \le i \le m.$ When the origin is not a vertex of the feasible region, we need a process to find some vertex of the feasible region. This is called the **initialization phase** or **Phase I** of the simplex algorithm.

## Auxiliary linear program 

We say that a linear program is **feasible** if its feasible region is non-empty. The initialization phase determines if a standard linear program is feasible and if it is then finds a vertex of the feasible region. To do this we create an auxiliary linear program whose *optimal* solution provides a *feasible* solution of the original linear program.

The auxiliary linear program of the standard linear program \@ref(eq:standard-lp) is defined as follows:
\begin{equation}
  \begin{array}{lrrrrrrrrrrr}
    \mbox{maximize: } &  &  &   &  & &  & & - & x_0 & \\
    \mbox{subject to: } 
      & & & a_{11} x_1 & + & \dots & + & a_{1n} x_n & - &x_0 & \leq & b_1 \\
      & & & a_{21} x_1 & + & \dots & + & a_{2n} x_n & - &x_0 & \leq & b_2 \\
      & & & & & \vdots &  \\
      & & & a_{m1} x_1 & + & \dots & + & a_{mn} x_n & - &x_0 & \leq & b_m \\
      & & & x_1, & x_2, & \dots &, & x_n & , & x_0 & \geq & 0
  \end{array} 
  (\#eq:auxiliary-lp)
\end{equation}

One can show, using the [extreme value theorem](https://en.wikipedia.org/wiki/Extreme_value_theorem), that the auxiliary linear program \@ref(eq:auxiliary-lp) always has an optimal solution. Furthermore, using some basic algebraic manipulations one can prove the following theorem.

::: {.theorem}

Suppose $(k_1, k_2, \dots, k_n, k_0)$ is an optimal solution of the auxiliary linear program \@ref(eq:auxiliary-lp). Then, the standard linear program \@ref(eq:standard-lp) is feasible if and only if $k_0 = 0$. In this case, $(k_1, k_2, \dots, k_n)$ is a vertex of the feasible region of \@ref(eq:standard-lp).
:::

To understand the auxiliary linear program, it is better to write it in the following non-standard form:
\begin{equation}
  \begin{array}{lrrrrrrrrrrr}
    \mbox{minimize: } & & & & & & & & & & & x_0 & \\
    \mbox{subject to: } 
      & & & a_{11} x_1 & + & \dots & + & a_{1n} x_n & \leq & b_1 & + & x_0 \\
      & & & a_{21} x_1 & + & \dots & + & a_{2n} x_n & \leq & b_2 & + & x_0 \\
      & & & & & \vdots &  \\
      & & & a_{m1} x_1 & + & \dots & + & a_{mn} x_n & \leq & b_m & + & x_0 \\
      & & & x_1, & x_2, & \dots &, & x_n & , & x_0 & \geq & 0
  \end{array} 
\end{equation}

We can then interpret $x_0$ as a relaxation of the constraints. The auxiliary linear program is then asking - *what is the smallest constraint relaxation necessary to make our linear program feasible?*. The primary linear program is feasible if and only if no relaxation is necessary.

If the origin is not a vertex of the feasible region, then the method of solving the standard linear program \@ref(eq:standard-lp), starting with **Phase I**, is as follows:

1. Form the auxiliary linear program and its tableau. Note that we still cannot proceed normally as even for the auxiliary linear program the $b_i$'s are not all non-negative.
2. Perform a pivot operation about the entry in the column corresponding to the variable $x_0$ and the row corresponding to the *most negative $b_i$*. This results in a dictionary where all the $b_i$'s are now non-negative.
3. Solve the auxiliary linear program using the simplex method.

Suppose $(k_1, k_2, \dots, k_n, k_0)$ is an optimal solution of the auxiliary linear program. If $k_0 \neq 0$, then we halt as the primary linear program is not feasible. If $k_0 = 0$, then we proceed to **Phase II** with the *initial* vertex $(k_1, \dots, k_n)$.

4. Find the dictionary at the *initial* vertex and proceed with the simplex method to find an optimal solution. 


## Combined tableau 

There is a shortcut to combining both Phase I and Phase II and reduce the number of pivots necessary. We create a *combined tableau* which contains information about both the auxiliary linear program and the primary linear program as follows:

\begin{equation}
  \begin{array}{rrrrrrrrrrrr|l}
      c_1  & & \dots & & c_{n}  & 0 & & 0 & \dots & & 0 & 0 & 0\\ \hline
      0  & & \dots & & 0  & 0 & & 0 & \dots & & 0 & -1 & 0\\ \hline
      a_{11}  & & \dots & & a_{1n}  & 1 & & & & & & -1 &b_1\\
      a_{21}  & & \dots & & a_{2n}  & & & 1 & & & & -1 &b_2\\
      & & & & & \vdots & & & & & & \vdots & \vdots \\
      a_{m1}  & & \dots & & a_{mn}  & & & & & & 1 & -1 &b_m\\
  \end{array} 
\end{equation}

The first row of the tableau is the objective function of the primary linear program and the second row of the tableau is the objective of the auxiliary linear program. We use the combined tableau to first perform Phase I and then neglect the auxiliary objective and the variable $x_0$ and proceed on to Phase II using the same tableau.

::: {.example}

Consider the following linear program:
\begin{equation}
  \begin{array}{rrrrrl}
  \mbox{maximize:} & x & + & y \\
  \mbox{subject to:}
    & x & + & 2y & \le & 6 \\
    & -x &  &  & \ge & -1 \\
    &  &  & -y & \ge & -2 \\
    & x & , & y & \ge & 0.
  \end{array}
\end{equation}

It is easy to see that feasible region is given by the triangle with vertices $(1,2)$, $(2,2)$, and $(1, 2.5)$ and the optimal solution is given by $(2,2)$. 

Because $(0,0)$ is not feasible, we need the two-phase simplex method to solve this problem. We start with the combined tableau: 

\begin{align}
  \begin{bmatrix}
    1 & 1 & 0 & 0 & 0 & 0 & 0 \\
    0 & 0 & 0 & 0 & 0 & -1 & 0 \\
    1 & 2 & 1 & 0 & 0 & -1 & 6 \\
    -1 & 0 & 0 & 1 & 0 & -1 & -1 \\
    0 & -1 & 0 & 0 & 1 & \boxed{-1} & -2
  \end{bmatrix}
\end{align}

The first pivot is in the column corresponding to the variable $x_0$ and the row corresponding to the *most negative $b_i$* (which is the last row). This results in the following combined tableau:

\begin{align}
  \begin{bmatrix}
    1 & 1 & 0 & 0 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 & -1 & 0 & 2 \\
    1 & 3 & 1 & 0 & -1 & 0 & 8 \\
    -1 & 1 & 0 & 1 & -1 & 0 & 1 \\
    0 & 1 & 0 & 0 & -1 & 1 & 2
  \end{bmatrix}
\end{align}

We then continue with the standard simplex method to find the solution:

\begin{align}
  \begin{bmatrix}
    0 & 0 & 0 & 1 & 1 & -2 & -3 \\
    0 & 0 & 0 & 0 & 0 & -1 & \boxed{0} \\
    0 & 0 & 1 & 1 & 2 & -4 & 1 \\
    0 & 1 & 0 & 0 & -1 & 1 & 2 \\
    1 & 0 & 0 & -1 & 0 & 1 & 1
  \end{bmatrix}
\end{align}

We see that the optimal value is 0 and hence the primary linear program is feasible. We then remove the auxiliary objective and coefficient to get the following tableau for the primary linear program:


\begin{align}
  \begin{bmatrix}
    0 & 0 & 0 & 1 & 1  & -3 \\
    0 & 0 & 1 & \boxed{1} & 2  & 1 \\
    0 & 1 & 0 & 0 & -1 & 2 \\
    1 & 0 & 0 & -1 & 0 & 1
  \end{bmatrix}
\end{align}

We continue solving this using the simplex method to get the final tableau

\begin{align}
  \begin{bmatrix}
    0 & 0 & -1 & 0 & -1 & -4 \\
    0 & 0 & 1 & 0 & 2 & 1 \\
    0 & 1 & 0 & 1 & -1 & 2 \\
    1 & 0 & 1 & 0 & 2 & 2
  \end{bmatrix}
\end{align}

The final non-basic variables are $w_1$ and $w_3$ and the basic variables are $x, y, w_2$ with values $2, 2, 1$, respectively. The optimal objective value is $4$.

:::